/* ================================================================
   LaTaberna - PubPOS — MÓDULO JS (ES6)
   Archivo: js/roles.js
   Versión: 2.0.3
   Propósito: Definición de roles, jerarquía y matriz de permisos.
              v2.0.3: documentada la decisión de mantener verMesas
                      false para cliente. El READ en Appwrite sobre
                      laTaberna_Mesas no habilita la vista de mesas.
   ================================================================ */

export const Roles = {
  lista: [
    'master',
    'admin',
    'gerente',
    'chef',
    'cocinaAyudante',
    'barman',
    'barraAyudante',
    'mesero',
    'caja',
    'repartidor',
    'artista',
    'cliente'
  ],

  jerarquia: {
    master: ['admin'],
    admin: [
      'gerente',
      'chef',
      'cocinaAyudante',
      'barman',
      'barraAyudante',
      'mesero',
      'caja',
      'repartidor',
      'artista'
    ],
    gerente: [
      'chef',
      'cocinaAyudante',
      'barman',
      'barraAyudante',
      'mesero',
      'caja',
      'repartidor',
      'artista'
    ]
  },

  permisos: {
    master: {
      verMesas: true,
      verCocina: true,
      verCaja: true,
      verConfig: true,
      verMenu: true,
      verEventos: true,
      verDelivery: true,
      gestionarPedido: true,
      tomarPedido: true,
      enviarComanda: true,
      cambiarEstadoComanda: true,
      cerrarMesa: true,
      editarProductos: true,
      editarPrecios: true,
      editarRecetas: true,
      editarInventario: true,
      verCostos: true,
      gestionarPersonal: true,
      asignarAdmin: true,
      asignarGerente: true,
      asignarStaff: true,
      gestionarDelivery: true,
      gestionarEventos: true
    },
    admin: {
      verMesas: true,
      verCocina: true,
      verCaja: true,
      verConfig: true,
      verMenu: true,
      verEventos: true,
      verDelivery: true,
      gestionarPedido: true,
      tomarPedido: true,
      enviarComanda: true,
      cambiarEstadoComanda: true,
      cerrarMesa: true,
      editarProductos: true,
      editarPrecios: true,
      editarRecetas: true,
      editarInventario: true,
      verCostos: true,
      gestionarPersonal: true,
      asignarAdmin: false,
      asignarGerente: true,
      asignarStaff: true,
      gestionarDelivery: true,
      gestionarEventos: true
    },
    gerente: {
      verMesas: true,
      verCocina: true,
      verCaja: true,
      verConfig: false,
      verMenu: true,
      verEventos: true,
      verDelivery: true,
      gestionarPedido: true,
      tomarPedido: true,
      enviarComanda: true,
      cambiarEstadoComanda: true,
      cerrarMesa: true,
      editarProductos: true,
      editarPrecios: true,
      editarRecetas: true,
      editarInventario: true,
      verCostos: true,
      gestionarPersonal: true,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: true,
      gestionarDelivery: true,
      gestionarEventos: true
    },
    chef: {
      verMesas: false,
      verCocina: true,
      verCaja: false,
      verConfig: false,
      verMenu: false,
      verEventos: false,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: true,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: true,
      editarInventario: true,
      verCostos: true,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    },
    cocinaAyudante: {
      verMesas: false,
      verCocina: true,
      verCaja: false,
      verConfig: false,
      verMenu: false,
      verEventos: false,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: true,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    },
    barman: {
      verMesas: false,
      verCocina: true,
      verCaja: false,
      verConfig: false,
      verMenu: false,
      verEventos: false,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: true,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: true,
      editarInventario: true,
      verCostos: true,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    },
    barraAyudante: {
      verMesas: false,
      verCocina: true,
      verCaja: false,
      verConfig: false,
      verMenu: false,
      verEventos: false,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: true,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    },
    mesero: {
      verMesas: true,
      verCocina: false,
      verCaja: false,
      verConfig: false,
      verMenu: true,
      verEventos: false,
      verDelivery: false,
      gestionarPedido: true,
      tomarPedido: true,
      enviarComanda: true,
      cambiarEstadoComanda: false,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    },
    caja: {
      verMesas: true,
      verCocina: false,
      verCaja: true,
      verConfig: false,
      verMenu: false,
      verEventos: false,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: false,
      cerrarMesa: true,
      editarProductos: false,
      editarPrecios: true,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    },
    repartidor: {
      verMesas: false,
      verCocina: false,
      verCaja: false,
      verConfig: false,
      verMenu: false,
      verEventos: false,
      verDelivery: true,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: false,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: true,
      gestionarEventos: false
    },
    artista: {
      verMesas: false,
      verCocina: false,
      verCaja: false,
      verConfig: false,
      verMenu: false,
      verEventos: true,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: false,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: true
    },
    cliente: {
      // verMesas se mantiene false para evitar acceso a la vista de
      // mapa de mesas. El permiso READ en Appwrite sobre laTaberna_Mesas
      // solo permite consultas puntuales de estado de mesa, no habilita
      // esta vista.
      verMesas: false,
      verCocina: false,
      verCaja: false,
      verConfig: false,
      verMenu: true,
      verEventos: true,
      verDelivery: false,
      gestionarPedido: false,
      tomarPedido: false,
      enviarComanda: false,
      cambiarEstadoComanda: false,
      cerrarMesa: false,
      editarProductos: false,
      editarPrecios: false,
      editarRecetas: false,
      editarInventario: false,
      verCostos: false,
      gestionarPersonal: false,
      asignarAdmin: false,
      asignarGerente: false,
      asignarStaff: false,
      gestionarDelivery: false,
      gestionarEventos: false
    }
  },

  getPermisos(rol) {
    return this.permisos[rol] || this.permisos.cliente;
  },

  puedeAsignar(rolActual, rolObjetivo) {
    if (!this.lista.includes(rolObjetivo)) return false;
    if (rolActual === 'master') return rolObjetivo === 'admin';
    const permitidos = this.jerarquia[rolActual] || [];
    return permitidos.includes(rolObjetivo);
  }
};